services:
  postgres:
    image: postgres:16-alpine
    container_name: ecom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom_secret
      POSTGRES_DB: ecom_admin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ecom -d ecom_admin']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass ecom_redis_secret
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'ecom_redis_secret', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
